sudo: required
language: python
dist: trusty
services:
- docker
before_script:
- docker --version
- docker-compose --version
script:
- chmod -R 0777 ./home
- docker-compose build --no-cache
- docker images
- docker-compose up -d --force-recreate
- sleep 10
- docker ps
- chmod ugo+x tests/test.sh && bash tests/test.sh
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=vietdien2005/shinken-webui2-base
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -f ./jenkins-alpine/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
env:
  matrix:
  - secure: SnYFFvdGw9c/lHSY+5gKs+gOJC0WTcKZ88jDWBLY/BCXngc/aOZiH7eZA9cAXf8fBwFT0PGnn6I+p6J6Gvz+9scsyDcogEJt379jG8napsKUVIcTc0kz6XJKY65HDTvb8HZdgq3L9wM2h2uyqvkxE8jCvvqIx1xd4nPI0oC6nQT1dOEaHMJj71aAFpeLmWa+LY+pGp63wqapUZ+NcOuqkxK3XdXnKVz4OG7bH4bgagzXEhouUb/DDqAh7fdit4T5AyV0zSHk1uXSITSDdXcDn4rbBFXI6w6JwXacllvvUOb3Llj3SvQzLxRTKKFjPmMooBL5LppepdGdF43To9yBUGF0qd7idlQqQSurYwbNLLALYc2OX/xAUUI9J47j+JgzgB6yIrezf79rGSmVIyUt/adE1ZgqLg+32JJXcD5hwCdmfMfzhirLN0XTWhMaFxjd0PCe27yBG4nbqxXVCWNWrgSe1e51/3wRLeAU/bAtz+bwOzg+eV+utiRSCvV14C8pgPMggPoDJCa8HMrLOaAbDN55VldFCqbDHrN1k7jDesr0+Ur1OGvlTlJ1ky96u2LC+BcB/HCKRRHWsEfoF66lvwvtUz+U9gKDoDngxlohID1xZVrvaDlrAi4v9s6B9NNHX5kLIwwjxIZtywhEuo41ukbbdy37sJlqpWFx4Mr8EPI=
  - secure: n0bLygTyrSiuZVJxGrZW81DirqZM5s4zEPIgmzgTzivTSzbAfmv3PYNiLqIhj18KL7xyNmJkzPG6aIr74d+edh2A3mZfVuTDfBVnJv6CK605bsheMBcY3V+d57HmpIkXNQC/aPMrAbDmGQ5H7Syda1nSqZaaCwrbrYcQ0+m69GXXFqVyG8MJblfnHQhk5oQMsBmrJBH4G2X8zcruN56At1Y3/ZsIYYANi01zvJwOD7myJjdNbem2uqeK9Fe3Hq1IqDu7Yn1kNQHLsiLM04V7NSKXokgDlbhJ13e7hE1EpWmg34L7v0dylNsPJpFwAmImZQZlMy9J/qXxG5mvT2Q638lMUzYkBNc7gKbHGT+ZNNBba/XsNFM+1sXQ5eWxUT6mL7XFJo8l4Z+DO70FU6x1reMYk68vtC8A9TOi2h95VNYcKbzjqKN1XzW57m/tYAwq5415ZH0aP0EczNDc1yW7bCvIdAQiEVLoXmuwrB2N6PvnZ3IhcY0dz4JtNzqYq3RUtihbJ58iGyIze28XgXt+sTy6o0z+BPf/EcSsrvWSfiRHFiww9GUVNFCnI7fMatngEUOCqoM3lkagHMD8MM6fVXQ69pz0M3Eo11diYv2UBJp3rHTgniw1YHMkJN8oGJ90vPNRmYrw6E4Pl1HhH3dkF8cT6AItgzacMGwmFuv/cLw=
